### ISSUE TITLE
Fails to build with GHC 9.6

### ISSUE THREAD

**Issue by benz0li** [jacobstanley/unix-compat#64] opened 2023-03-14 05:12 UTC
```
Failed to build unix-compat-0.6.
Build log (
/root/.cache/cabal/logs/ghc-9.6.1/unix-compat-0.6-73d562a73c383869615c703309240a5749e815bd9ef425c168b33c8df83a4ed4.log
):
Configuring library for unix-compat-0.6..
Preprocessing library for unix-compat-0.6..
Building library for unix-compat-0.6..
[1 of 8] Compiling System.PosixCompat.Files ( dist/build/System/PosixCompat/Files.hs, dist/build/System/PosixCompat/Files.o, dist/build/System/PosixCompat/Files.dyn_o )
[2 of 8] Compiling System.PosixCompat.Temp ( src/System/PosixCompat/Temp.hs, dist/build/System/PosixCompat/Temp.o, dist/build/System/PosixCompat/Temp.dyn_o )
[3 of 8] Compiling System.PosixCompat.Time ( src/System/PosixCompat/Time.hs, dist/build/System/PosixCompat/Time.o, dist/build/System/PosixCompat/Time.dyn_o )
[4 of 8] Compiling System.PosixCompat.Types ( src/System/PosixCompat/Types.hs, dist/build/System/PosixCompat/Types.o, dist/build/System/PosixCompat/Types.dyn_o )
[5 of 8] Compiling System.PosixCompat.Extensions ( dist/build/System/PosixCompat/Extensions.hs, dist/build/System/PosixCompat/Extensions.o, dist/build/System/PosixCompat/Extensions.dyn_o )
[6 of 8] Compiling System.PosixCompat.Unistd ( src/System/PosixCompat/Unistd.hs, dist/build/System/PosixCompat/Unistd.o, dist/build/System/PosixCompat/Unistd.dyn_o )
[7 of 8] Compiling System.PosixCompat.User ( dist/build/System/PosixCompat/User.hs, dist/build/System/PosixCompat/User.o, dist/build/System/PosixCompat/User.dyn_o )

src/System/PosixCompat/User.hsc:20:7: error: [GHC-76037]
    Not in scope: type constructor or class ‘GroupEntry’
   |
20 |     , GroupEntry(..)
   |       ^^^^^^^^^^^^^^

src/System/PosixCompat/User.hsc:26:7: error: [GHC-76037]
    Not in scope: type constructor or class ‘UserEntry’
   |
26 |     , UserEntry(..)
   |
```

**Comment by benz0li** [comment] 2023-03-14 05:13
[Not in scope [GHC-76037] — Haskell Error Index](https://errors.haskell.org/messages/GHC-76037/)

**Comment by mitchellwrosen** [comment] 2023-03-14 17:47
Duplicate of #61. This will be addressed soon (in a new repo)

**Closed as completed** 2023-03-14 18:12 UTC
